export const ERROR_CODES = {
  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',

  // Authentication
  INVALID_API_KEY: 'INVALID_API_KEY',
  API_KEY_REQUIRED: 'API_KEY_REQUIRED',
  INVALID_JWT: 'INVALID_JWT',
  JWT_EXPIRED: 'JWT_EXPIRED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NONCE_EXPIRED: 'NONCE_EXPIRED',
  NONCE_ALREADY_USED: 'NONCE_ALREADY_USED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  INVALID_WALLET_ADDRESS: 'INVALID_WALLET_ADDRESS',
  TIER_REQUIRED: 'TIER_REQUIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Operators
  OPERATOR_NOT_FOUND: 'OPERATOR_NOT_FOUND',
  INVALID_OPERATOR_ID: 'INVALID_OPERATOR_ID',

  // Strategies
  STRATEGY_NOT_FOUND: 'STRATEGY_NOT_FOUND',

  // AVS
  AVS_NOT_FOUND: 'AVS_NOT_FOUND',

  // Stakers
  STAKER_NOT_FOUND: 'STAKER_NOT_FOUND',

  // Query Validation
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  INVALID_PAGINATION: 'INVALID_PAGINATION',
  INVALID_SORT_FIELD: 'INVALID_SORT_FIELD',
  INVALID_FILTER: 'INVALID_FILTER',

  // Data Issues
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
  DATA_NOT_AVAILABLE: 'DATA_NOT_AVAILABLE',
  STALE_DATA: 'STALE_DATA',

  // Database
  DATABASE_ERROR: 'DATABASE_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  QUERY_TIMEOUT: 'QUERY_TIMEOUT',

  // Cache
  CACHE_ERROR: 'CACHE_ERROR',

  // Comparison
  TOO_MANY_OPERATORS_TO_COMPARE: 'TOO_MANY_OPERATORS_TO_COMPARE',
  DUPLICATE_OPERATORS_IN_COMPARISON: 'DUPLICATE_OPERATORS_IN_COMPARISON',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
